import json, os
from playwright.sync_api import sync_playwright
import os as _os
ROOT = _os.environ.get("G19S_TEST_ROOT", "/tmp/g19s-test")
H = ROOT + "/gui/home"; SET = H + "/.config/g19s/settings.json"; MAC = H + "/.config/g19s/macros.json"
def ok(c, m): print(("OK   " if c else "FEHL ") + m)
def cfg(): return json.load(open(SET))
errors = []
with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={"width": 1280, "height": 1100})
    pg.on("dialog", lambda d: d.accept()); pg.on("pageerror", lambda e: (errors.append(str(e)), print("SEITENFEHLER", e)))
    pg.goto("http://127.0.0.1:8799/#testtoken"); pg.wait_for_selector(".gkey")
    # Lautstärke-Aktion
    pg.click(".gkey >> text=G10"); pg.click(".types button >> text=Lautstärke")
    pg.select_option("#editor select", "mute"); pg.click("#applyBtn"); pg.wait_for_timeout(400)
    ok(json.load(open(MAC))["profiles"][0]["keys"]["M1"]["G10"] == {"volume": "mute"}, "G10 = Lautstärke stumm")
    ok("Stumm" in pg.inner_text(".gkey >> nth=9"), "Kachel zeigt „Stumm“")
    # Seiten, Nachtmodus, Bildschirmschoner
    pg.click("nav >> text=Beleuchtung"); pg.wait_for_timeout(400)
    ok(pg.locator(".pagerow").count() == 11, "11 Displayseiten aufgelistet")
    rows = pg.locator(".pagerow")
    names = [rows.nth(i).locator(".pn").inner_text() for i in range(7)]
    ok(names[:4] == ["Uhr", "Musik", "Wetter", "Termine"], "Standardreihenfolge: " + ", ".join(names))
    pg.locator(".pagerow", has_text="Makros").locator("input").uncheck()
    pg.locator(".pagerow", has_text="Hardware").locator("button[title='nach oben']").click()
    pg.select_option("#startPage", label="Wetter")
    pg.check("#nightOn"); pg.fill("#nightStart", "23:15"); pg.fill("#nightEnd", "06:45")
    pg.click("#nightMode >> text=Display ausschalten")
    ok(not pg.is_visible("#nightDimRow"), "Helligkeitsregler bei „ausschalten“ ausgeblendet")
    pg.check("#saverOn"); pg.fill("#saverMin", "10"); pg.select_option("#saverPage", "weather"); pg.fill("#volStep", "10")
    pg.select_option("#pvPages", "4"); pg.wait_for_timeout(600)
    pg.screenshot(path=ROOT + "/shots/14_display.png", full_page=True)
    pg.click("#saveSettings"); pg.wait_for_timeout(400)
    s = cfg()
    ok(s["layer_pages"]["M1"] == ["clock", "music", "weather", "hardware", "calendar", "slides"], "Seiten M1 gespeichert: " + ",".join(s["layer_pages"]["M1"]))
    ok("macros" in s["layer_pages"]["M2"] and "macros" in s["pages"], "M2 unverändert, Gesamtliste enthält Makros")
    # eigene Seiten je Ebene
    pg.click("#plLayers >> text=M3"); pg.wait_for_timeout(300)
    ok("active" in pg.get_attribute("#pvProfiles >> text=M3", "class"), "Ebene M3 auch in der Vorschau gewählt")
    for nm in ["Musik", "Wetter", "Termine", "Hardware", "Makros", "Bilder"]:
        pg.locator(".pagerow", has=pg.get_by_text(nm, exact=True)).locator("input").uncheck()
    ok(pg.locator(".pagerow:not(.off)").count() == 1, "M3: nur noch Uhr an")
    pg.click("#plLayers >> text=M2"); pg.wait_for_timeout(200)
    pg.locator(".pagerow", has=pg.get_by_text("Uhr", exact=True)).locator("input").uncheck()
    pg.click("#saveSettings"); pg.wait_for_timeout(400)
    s = cfg()
    ok(s["layer_pages"]["M3"] == ["clock"] and "clock" not in s["layer_pages"]["M2"] and "clock" in s["layer_pages"]["M1"], "Uhr nur in M1 und M3: " + str({k: len(v) for k, v in s["layer_pages"].items()}))
    pg.click("#plLayers >> text=M3"); pg.wait_for_timeout(300)
    pg.screenshot(path=ROOT + "/shots/18_ebenenseiten.png", full_page=True)
    pg.click("#plLayers >> text=M1"); pg.click("#plCopy"); pg.click("#saveSettings"); pg.wait_for_timeout(400)
    s = cfg()
    ok(s["layer_pages"]["M2"] == s["layer_pages"]["M3"] == s["layer_pages"]["M1"], "Auf alle Ebenen übertragen")
    ok(s["start_page"] == 4, "Startseite Wetter")
    ok(s["night"] == {"enabled": True, "start": "23:15", "end": "06:45", "mode": "off", "brightness": 10, "backlight_off": True}, "Nachtmodus gespeichert")
    ok(s["screensaver"] == {"enabled": True, "minutes": 10, "page": "weather"} and s["volume_step"] == 10, "Bildschirmschoner + Lautstärkeschritt gespeichert")
    # Diashow aus Ordner
    pg.click("nav >> text=Diashow"); pg.click("#slSource >> text=Ordner")
    ok(pg.is_visible("#folderBlock") and not pg.is_visible("#pwBlock"), "Ordner-Ansicht statt Piwigo")
    pg.click("#fdBrowse"); pg.wait_for_timeout(500)
    pg.click(".frow >> text=Bilder"); pg.wait_for_timeout(500)
    ok("1 Bild" in pg.inner_text(".fhead"), "Ordnerbrowser zeigt Bildanzahl: " + pg.inner_text(".fhead").replace("\n", " "))
    pg.click("text=Diesen Ordner wählen"); pg.wait_for_timeout(200)
    ok(pg.input_value("#fdPath") == "~/Bilder", "Ordner übernommen")
    pg.click("#slTest"); pg.wait_for_timeout(1200)
    ok("4 Bilder" in pg.inner_text("#slTestInfo"), "Test mit Unterordnern: " + pg.inner_text("#slTestInfo"))
    pg.screenshot(path=ROOT + "/shots/15_ordner.png", full_page=True)
    pg.click("#saveSettings"); pg.wait_for_timeout(400)
    ok(cfg()["slideshow"]["source"] == "folder" and cfg()["slideshow"]["folder"] == "~/Bilder", "Ordnerquelle gespeichert")
    # Infoseiten
    pg.click("nav >> text=Infoseiten"); pg.wait_for_timeout(600)
    pg.fill("#wxQ", "leipzig"); pg.click("#wxForm button"); pg.wait_for_timeout(700)
    ok(pg.locator("#wxResults .res").count() == 2, "Ortssuche liefert 2 Treffer")
    pg.locator("#wxResults .res").first.click(); pg.wait_for_timeout(900)
    ok("15°" in pg.inner_text("#wxTest") and "Leipzig" in pg.inner_text("#wxName"), "Ort gewählt, Wetter geprüft: " + pg.inner_text("#wxTest"))
    pg.click("#calAdd"); r = pg.locator(".srcrow").last.locator("input")
    r.nth(0).fill("Privat"); r.nth(1).fill("http://127.0.0.1:8812/privat.ics")
    pg.click(".srcrow >> text=Testen"); pg.wait_for_timeout(800)
    ok("Anmeldung fehlgeschlagen" in pg.inner_text("#calSources"), "Ohne Passwort: Fehler gemeldet: " + pg.inner_text("#calSources")[-80:].replace("\n", " "))
    r.nth(2).fill("max"); r.nth(3).fill("geheim")
    pg.click(".srcrow >> text=Testen"); pg.wait_for_timeout(800)
    ok("Termine in den nächsten 30 Tagen" in pg.inner_text("#calSources") and "Teamrunde" in pg.inner_text("#calSources"), "Mit Passwort: Termine gefunden")
    pg.click("#calAdd"); r2 = pg.locator(".srcrow").last.locator("input")
    r2.nth(0).fill("Falsch"); r2.nth(1).fill("http://127.0.0.1:8812/kaputt.ics")
    pg.locator(".srcrow").last.locator("text=Testen").click(); pg.wait_for_timeout(800)
    ok("Webseite statt Kalenderdaten" in pg.inner_text("#calSources"), "Falsche Adresse erkannt")
    pg.locator(".srcrow").last.locator("button[title=entfernen]").click(); pg.wait_for_timeout(200)
    pg.click("#calAdd"); r3 = pg.locator(".srcrow").last.locator("input")
    r3.nth(0).fill("Nextcloud"); r3.nth(1).fill("http://127.0.0.1:8812/nc/remote.php/dav"); r3.nth(2).fill("mde@example.de"); r3.nth(3).fill("app-pw")
    pg.locator(".srcrow").last.locator("text=Testen").click(); pg.wait_for_timeout(1500)
    t3 = pg.inner_text("#calSources")
    ok("aus 6 Kalendern: Persönlich, Geburtstage von Kontakten, Marco" in t3 and "Geburtstag Oma" in t3, "Nextcloud-Konto: Kalender gefunden: " + t3.replace("\n", " ")[-120:])
    pg.screenshot(path=ROOT + "/shots/17_nextcloud.png", full_page=True)
    pg.locator(".srcrow").last.locator("button[title=entfernen]").click(); pg.wait_for_timeout(200)
    pg.fill("#ntIgnore", "Discover"); pg.fill("#ntSec", "8")
    pg.click("#ntTest"); pg.wait_for_timeout(500)
    ok("Testbenachrichtigung" in open(ROOT + "/state/notify.log").read(), "Testbenachrichtigung über notify-send")
    pg.click("#hwRefresh"); pg.wait_for_timeout(500)
    ok("Laufwerke" in pg.inner_text("#hwInfo"), "Hardwarewerte angezeigt")
    pg.screenshot(path=ROOT + "/shots/16_info.png", full_page=True)
    pg.click("#saveSettings"); pg.wait_for_timeout(400)
    s = cfg()
    ok(s["weather"] == {"name": "Leipzig", "lat": 51.34, "lon": 12.37}, "Wetter-Ort gespeichert")
    ok([x["name"] for x in s["calendar"]["sources"]] == ["Privat"] and s["calendar"]["sources"][0]["password"] == "geheim", "Kalender gespeichert")
    ok(s["notifications"] == {"enabled": True, "seconds": 8, "ignore": "Discover"}, "Benachrichtigungen gespeichert")
    # Vorschau der neuen Seiten (vom Server gerendert)
    pg.click("nav >> text=Beleuchtung"); pg.select_option("#pvPages", "4"); pg.wait_for_timeout(1500)
    ok((pg.get_attribute("#lcd", "src") or "").startswith("data:image/png"), "Vorschau Wetterseite")
    b.close()
print("Seitenfehler:", errors or "keine")
